# Generated by Django 4.2.7 on 2024-01-12 20:31

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(dimensions=10)),
                ('chunk_idx', models.IntegerField()),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=10)),
                ('chunks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyModels.chunk')),
            ],
        ),
    ]
