repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace


- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff
      args: ['--fix']
      types_or: [python, pyi, jupyter]



- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.1
  hooks:
    - id: markdownlint-cli2
      args: ['--fix']
