"""
Django settings for copywriter project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from drfboilerplate.settings.prod import *  # noqa: F403, F401

DEBUG = True

DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3"}}
