# Generated by Django 5.0.2 on 2024-02-25 15:13

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("embedding", pgvector.django.VectorField(dimensions=10)),
                ("chunk_idx", models.IntegerField()),
                ("start_char", models.IntegerField()),
                ("end_char", models.IntegerField()),
            ],
        ),
    ]
