# Generated by Django 4.2.13 on 2024-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chunks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="text",
            field=models.CharField(max_length=1000),
        ),
    ]
