# Generated by Django 5.0.2 on 2024-03-29 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="embedding",
        ),
    ]
