name: Lint shell scripts

on: 
  pull_request:
    types:
      - opened

jobs:
  shellcheck:
    name: shellcheck, lint
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
